services:
  safebucket:
    container_name: safebucket
    image: safebucket:latest
    environment:
      - APP__API_URL=${APP__API_URL}
      - APP__WEB_URL=${APP__WEB_URL}
      - APP__PORT=${APP__PORT}
      - APP__TRUSTED_PROXIES=${APP__TRUSTED_PROXIES}
      - APP__STATIC_FILES__ENABLED=${APP__STATIC_FILES__ENABLED}
      - APP__STATIC_FILES__DIRECTORY=${APP__STATIC_FILES__DIRECTORY}
      - DATABASE__HOST=db
      - DATABASE__PORT=5432
      - DATABASE__USER=${DATABASE__USER}
      - DATABASE__PASSWORD=${DATABASE__PASSWORD}
      - DATABASE__NAME=${DATABASE__NAME}
      - DATABASE__SSLMODE=disable
      - APP__JWT_SECRET=${APP__JWT_SECRET}
      - APP__ADMIN_EMAIL=${APP__ADMIN_EMAIL}
      - APP__ADMIN_PASSWORD=${APP__ADMIN_PASSWORD}
      - APP__ALLOWED_ORIGINS=${APP__ALLOWED_ORIGINS}
      - CACHE__TYPE=${CACHE__TYPE}
      - CACHE__REDIS__HOSTS=${CACHE__REDIS__HOSTS}
      - CACHE__REDIS__PASSWORD=${CACHE__REDIS__PASSWORD}
      - STORAGE__TYPE=${STORAGE__TYPE}
      - STORAGE__MINIO__BUCKET_NAME=${STORAGE__MINIO__BUCKET_NAME}
      - STORAGE__MINIO__ENDPOINT=${STORAGE__MINIO__ENDPOINT}
      - STORAGE__MINIO__CLIENT_ID=${STORAGE__MINIO__CLIENT_ID}
      - STORAGE__MINIO__CLIENT_SECRET=${STORAGE__MINIO__CLIENT_SECRET}
      - STORAGE__MINIO__TYPE=${STORAGE__MINIO__TYPE}
      - STORAGE__MINIO__JETSTREAM__TOPIC_NAME=${STORAGE__MINIO__JETSTREAM__TOPIC_NAME}
      - STORAGE__MINIO__JETSTREAM__HOST=${STORAGE__MINIO__JETSTREAM__HOST}
      - STORAGE__MINIO__JETSTREAM__PORT=${STORAGE__MINIO__JETSTREAM__PORT}
      - EVENTS__TYPE=${EVENTS__TYPE}
      - EVENTS__JETSTREAM__TOPIC_NAME=${EVENTS__JETSTREAM__TOPIC_NAME}
      - EVENTS__JETSTREAM__HOST=${EVENTS__JETSTREAM__HOST}
      - EVENTS__JETSTREAM__PORT=${EVENTS__JETSTREAM__PORT}
      - NOTIFIER__TYPE=${NOTIFIER__TYPE}
      - NOTIFIER__SMTP__HOST=${NOTIFIER__SMTP__HOST}
      - NOTIFIER__SMTP__PORT=${NOTIFIER__SMTP__PORT}
      - NOTIFIER__SMTP__USERNAME=${NOTIFIER__SMTP__USERNAME}
      - NOTIFIER__SMTP__PASSWORD=${NOTIFIER__SMTP__PASSWORD}
      - NOTIFIER__SMTP__SENDER=${NOTIFIER__SMTP__SENDER}
      - NOTIFIER__SMTP__ENABLE_TLS=${NOTIFIER__SMTP__ENABLE_TLS}
      - NOTIFIER__SMTP__SKIP_VERIFY_TLS=${NOTIFIER__SMTP__SKIP_VERIFY_TLS}
      - ACTIVITY__TYPE=${ACTIVITY__TYPE}
      - ACTIVITY__LOKI__ENDPOINT=${ACTIVITY__LOKI__ENDPOINT}
      - AUTH__PROVIDERS__KEYS=${AUTH__PROVIDERS__KEYS}
      - AUTH__PROVIDERS__LOCAL__NAME=${AUTH__PROVIDERS__LOCAL__NAME}
      - AUTH__PROVIDERS__LOCAL__TYPE=${AUTH__PROVIDERS__LOCAL__TYPE}

    ports:
      - "8080:8080"
    restart: no

  bucket:
    container_name: bucket
    image: docker.io/bitnami/minio:2024.11.7
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DISTRIBUTED_MODE_ENABLED=no
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/bitnami/minio/data"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  db:
    container_name: db
    image: bitnami/postgresql:16.4.0
    ports:
      - "5442:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 20

  redis:
    container_name: redis
    image: docker.io/bitnami/redis:7.4
    ports:
      - "6379:6379"
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - ALLOW_EMPTY_PASSWORD=false
      - REDIS_PASSWORD=${CACHE_REDIS_PASSWORD}
    volumes:
      - "redis_data:/bitnami/redis/data"

  valkey:
    profiles: [valkey]
    container_name: valkey
    image: docker.io/bitnami/valkey:8.1.3
    ports:
      - "6380:6379"
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - ALLOW_EMPTY_PASSWORD=false
      - VALKEY_PASSWORD=${CACHE_VALKEY_PASSWORD}
    volumes:
      - "valkey_data:/bitnami/valkey/data"

  mailpit:
    image: axllent/mailpit:v1.26.2
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - "mail_data:/data"
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 500
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      MP_SMTP_AUTH: root:root

  nats:
    image: nats:2.10-alpine
    container_name: nats
    ports:
      - "4222:4222"
    restart: unless-stopped
    command: [ "-js" ]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  loki:
    container_name: loki
    image: docker.io/grafana/loki:3.2.1
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - "3100:3100"
      - "7946:7946"
      - "9095:9095"
    volumes:
      - ./config/loki.yaml:/etc/loki/config.yaml
    depends_on:
      - bucket
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    container_name: grafana
    profiles: [debug]
    image: docker.io/grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki:3100
            jsonData:
              httpHeaderName1: "X-Scope-OrgID"
            secureJsonData:
              httpHeaderValue1: "tenant1"
        EOF
        /run.sh
    ports:
      - "3200:3000"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  minio_data:
  postgresql_data:
  mail_data:
  redis_data:
  valkey_data:
