version: "3"
services:
  bucket:
    container_name: bucket
    image: docker.io/bitnami/minio:2024.11.7
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DISTRIBUTED_MODE_ENABLED=no
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/bitnami/minio/data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  db:
    container_name: db
    image: bitnami/postgresql:16.4.0
    ports:
      - "5442:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 20

  redis:
    container_name: redis
    image: docker.io/bitnami/redis:7.4
    ports:
      - "6379:6379"
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - ALLOW_EMPTY_PASSWORD=false
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - "redis_data:/bitnami/redis/data"

  mailpit:
    image: axllent/mailpit:v1.20.2
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - "mail_data:/data"
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 500
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  minio_data:
  postgresql_data:
  mail_data:
  redis_data: