version: 2
updates:
  # Go modules (backend)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[deps]"
      include: "scope"

  # npm dependencies (frontend)
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[deps]"
      include: "scope"
    ignore:
      - dependency-name: "react"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "react-dom"
        update-types: [ "version-update:semver-major" ]

  # Docker-compose stack (local)
  - package-ecosystem: "docker-compose"
    directory: "/deployments/local"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[docker-compose:local]"
      include: "scope"

  # Docker-compose stack (dev)
  - package-ecosystem: "docker-compose"
    directory: "/deployments/dev"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[docker-compose:dev]"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[actions]"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "/deployment/aws/terraform"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[terraform-aws]"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[docker]"
      include: "scope"
