platform:
  api_url: http://localhost:1323
  web_url: http://localhost:3000

cors:
  allowed_origins:
    - http://127.0.0.1:3000
    - http://localhost:3000

database:
  host: localhost
  port: 5442
  password: root
  name: transferspace
  user: root
  ssl: false

redis:
  hosts:
    - localhost:6379
  port: 6379
  password: root

#storage:
#  type: minio
#  minio:
#    bucket_name: safebucket
#    endpoint: localhost:9000
#    client_id: minio-root-user
#    client_secret: minio-root-password
#    type: jetstream
#    jetstream:
#      topic_name: safebucket:notifications
#      host: localhost
#      port: 4222

storage:
  type: aws
  aws:
    bucket_name: supersafebucket-files
    sqs_name: s3-event-queue-supersafebucket-files

events:
  type: aws
  aws:
    region: eu-west-1
    account_id: 819351094115
    sqs_name: general-purpose-queue

mailer:
  host: localhost
  port: 1025
  username: root
  password: root
  sender: notifications@safebucket.io

jwt:
  secret: 6n5o+dFncio8gQA4jt7pUJrJz92WrqD25zXAa8ashxA

admin:
  username: admin@safebucket.io
  password: ChangeMePlease

auth:
  providers:

activity:
  type: loki
  endpoint: http://localhost:3100
