platform:
  api_url: http://localhost:1323
  web_url: http://localhost:3001

cors:
  allowed_origins:
    - http://127.0.0.1:3001
    - http://localhost:3001

database:
  host: localhost
  port: 5442
  password: root
  name: transferspace
  user: root
  ssl: false

redis:
  hosts:
    - localhost:6379
  port: 6379
  password: root

storage:
  endpoint: localhost:9000
  client_id: minio
  client_secret: minioSuperSecretDoNotShare

jwt:
  secret: 6n5o+dFncio8gQA4jt7pUJrJz92WrqD25zXAa8ashxA

auth:
  providers:
