platform:
  api_url: http://localhost:1323
  web_url: http://localhost:3000

cors:
  allowed_origins:
    - http://127.0.0.1:3000
    - http://localhost:3000

database:
  host: localhost
  port: 5442
  password: root
  name: transferspace
  user: root
  ssl: false

redis:
  hosts:
    - localhost:6379
  port: 6379
  password: root

storage:
  type: gcp
  gcp:
    bucket_name: safebucket-gcp
    project_id: atomic-kit-462909-u2
    subscription_name: safebucket-sub
    topic_name: safebucket-notifications

events:
  type: gcp
  gcp:
    project_id: atomic-kit-462909-u2
    topic_name: safebucket-mail-notifs
    subscription_name: safebucket-mail-notifs-sub

mailer:
  host: localhost
  port: 1025
  username: root
  password: root
  sender: notifications@safebucket.io

jwt:
  secret: 6n5o+dFncio8gQA4jt7pUJrJz92WrqD25zXAa8ashxA

admin:
  username: admin@safebucket.io
  password: ChangeMePlease

auth:
  providers:

activity:
  type: loki
  endpoint: http://localhost:3100
