platform:
  api_url: http://localhost:1323
  web_url: http://localhost:3000
  port: 8080
  trusted_proxies:
    - 127.0.0.1
    - ::1
  static_files:
    enabled: true
    directory: "web/dist"

cors:
  allowed_origins:
    - http://127.0.0.1:3000
    - http://localhost:3000
    - http://127.0.0.1:4173
    - http://localhost:4173

database:
  host: localhost
  port: 5442
  password: root
  name: safebucket
  user: root
  ssl: false

cache:
  type: redis # or valkey
  redis:
    hosts:
      - localhost:6379
    port: 6379
    password: root
  # valkey:
  #   hosts:
  #     - localhost:6380
  #   port: 6380
  #   password: root

storage:
  type: minio
  minio:
    bucket_name: safebucket
    endpoint: localhost:9000
    client_id: minio-root-user
    client_secret: minio-root-password
    type: jetstream
    jetstream:
      topic_name: safebucket:notifications
      host: localhost
      port: 4222

events:
  type: jetstream
  jetstream:
    topic_name: safebucket:notifications
    host: localhost
    port: 4222

notifier:
  type: smtp
  smtp:
    host: localhost
    port: 1025
    username: root
    password: root
    sender: notifications@safebucket.io
    enable_ssl: false      # Set to true for production SMTP servers
    skip_verify_ssl: true      # Set to false for production with valid certificates

jwt:
  secret: 6n5o+dFncio8gQA4jt7pUJrJz92WrqD25zXAa8ashxA

admin:
  username: admin@safebucket.io
  password: ChangeMePlease

auth:
  providers:

activity:
  type: loki
  endpoint: http://localhost:3100
