cors:
  allowed_origins:
    - http://127.0.0.1:3001
    - http://localhost:3001

database:
  host: localhost
  port: 5442
  password: root
  name: transferspace
  user: root
  ssl: false

jwt:
  secret: 6n5o+dFncio8gQA4jt7pUJrJz92WrqD25zXAa8ashxA

auth_providers:
  google_client_id: <CHANGE_ME>
  google_client_secret: <CHANGE_ME>
