app:
  log_level: info
  api_url: http://localhost:8080
  web_url: http://localhost:3000
  allowed_origins:
    - http://127.0.0.1:3000
    - http://localhost:3000
    - http://127.0.0.1:4173
    - http://localhost:4173
  port: 8080
  jwt_secret: 6n5o+dFncio8gQA4jt7pUJrJz92WrqD25zXAa8ashxA
  trusted_proxies:
    - 127.0.0.1
    - ::1
  static_files:
    enabled: true
    directory: "web/dist"
  admin_email: admin@safebucket.io
  admin_password: ChangeMePlease
  trash_retention_days: 7  # Files in trash will be automatically deleted after this many days

database:
  host: localhost
  port: 5432
  user: safebucket-user
  password: safebucket-password
  name: safebucket
  sslmode: disable

cache:
  type: redis # or valkey
  redis:
    hosts:
      - localhost:6379
    password: root
  # valkey:
  #   hosts:
  #     - localhost:6380
  #   password: root

storage:
  type: minio
  minio:
    bucket_name: safebucket
    endpoint: localhost:9000
    client_id: minio-root-user
    client_secret: minio-root-password

events:
  type: jetstream
  queues:
    notifications:
      name: safebucket-notifications
    bucket_events:
      name: safebucket-bucket-events
    object_deletion:
      name: safebucket-object-deletion
  jetstream:
    host: localhost
    port: 4222

notifier:
  type: smtp
  smtp:
    host: localhost
    port: 1025
    username: root
    password: root
    sender: notifications@safebucket.io
    enable_ssl: false      # Set to true for production SMTP servers
    skip_verify_ssl: true      # Set to false for production with valid certificates

auth:
  providers:
    local:
      type: local
      domains:
      sharing:
        allowed: true
        domains: []
#    okta:
#      type: oidc
#      name: Okta
#      domains: []
#      oidc:
#        client_id:
#        client_secret:
#        issuer:
#      sharing:
#        allowed: true
#        domains: []
#    google:
#      type: oidc
#      name: Google
#      domains: []
#      oidc:
#        client_id:
#        client_secret:
#        issuer:
#      sharing:
#        enabled: true
#        domains: []

activity:
  type: loki
  loki:
    endpoint: http://localhost:3100
