name: Test Quality
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: ls dir
      run : ls -lah .

    - name: ls dir
      run : ls -lah ../

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v6.1.0
      with:
        working-directory: ${{ github.workspace }}