name: Test Quality
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Go linter
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          args: --timeout=4m
          working-directory: ${{ github.workspace }}

      - name: Run security scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build Go app
        run: go build -v ./...

      - name: Run Go unit tests
        run: go test -v ./...

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Next dependencies
        run: npm ci
        working-directory: ${{ github.workspace }}/web

      - name: Run Next linter
        run: npm run lint
        working-directory: ${{ github.workspace }}/web

      - name: Build Next app
        run: npm run build
        working-directory: ${{ github.workspace }}/web
